kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-sc-claim-01
  namespace: default
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
